### ISSUE TITLE
Cannot hide/show menuview while animation is running

### ISSUE THREAD

**Issue by purepure** [matteogobbi/MGFashionMenuView#4]
This issue happen when I try to hide a menu while it is animating. Normally, user cannot interact with the menu in that time but when we try to call api (show/hide), it was aborted 

I hope this issue can be fixed because almost animation need to handle(cancel) at anytime

BR

**Comment by matteogobbi** [comment]
This is not an issue but a choice.
When the menu is animating it doesn't accept other action. 
Just when it finish to open or to hide, you can interact again with that.

**Comment by purepure** [comment]
I actually did that, but I think it is really cool if we can handle (call api) at anytime. Anw, function isAnimating can help to deal with that

BR
