### ISSUE TITLE
Cannot interact with view behind menuview

### ISSUE THREAD

**Issue by purepure** [matteogobbi/MGFashionMenuView#5]
I think this is a bug when you trying to draw the menu view on top of the others. When call method:[menu hide], the menuview still be a layer between user and the other view behind it -> deny any interaction with them.

**Comment by matteogobbi** [comment]
Just solved. Thank you.

**Comment by purepure** [comment]
Haven't tried it yet, but I believe that will be cool. Thank for your quick response!
cheer!
